Repository maulanasdqn/nextjs-tailwindcss-boilerplate, pull requests merged in 2023-02, with the labels that each got.

#1 improvement : update documentation
  README.md
Labels: documentation

#2 Improvement : add and set dependencies
  .env
  .env.example
  .husky/pre-commit
  .prettierrc
  .vscode/settings.json
  configs/index.ts
  jest.config.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  postcss.config.js
  services/Api/index.ts
  services/Auth/index.ts
  services/Token/index.ts
  stylelint.config.js
  styles/Home.module.css
  styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: enhancement

#3 improvment: add recomendation to README.md
  README.md
Labels: documentation

#4 improvement: add devenv nix
  .envrc
  .gitignore
  devenv.lock
  devenv.nix
  devenv.yaml
Labels: enhancement

#5 improvement: add ignore
  .eslintignore
  .prettierignore
  devenv.yaml
Labels: enhancement

#10 improvement: add base component
  components/Common/DropdownMenu.tsx
  components/Navbar/index.tsx
  package.json
  pages/index.tsx
  yarn.lock
Labels: enhancement

#11 improvement: auth logic
  hooks/Auth/useLogin.ts
  hooks/Common/useDebounce.ts
  hooks/Common/useIntersection.ts
  layouts/Auth/AuthLayouts.tsx
  layouts/Base/BaseLayouts.tsx
  modules/Auth/ProtectedRoutes.tsx
  pages/_app.tsx
  services/Auth/index.ts
  stores/Auth/index.ts
  utilities/types/Auth.ts
Labels: enhancement

#18 improvement: add auth pages
  README.md
  components/Common/TextField.tsx
  components/Navbar/index.tsx
  layouts/Auth/AuthLayouts.tsx
  layouts/Auth/types.d.ts
  pages/_app.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
  utilities/contant/index.ts
Labels: documentation, enhancement

#19 Fenny Oktaviani | Improvement Landing Page
  assets/hallo.png
  components/Common/DropdownMenu.tsx
  components/Footbar/index.tsx
  components/Image/index.tsx
  components/Navbar/index.tsx
  layouts/Base/BaseLayouts.tsx
  pages/index.tsx
Labels: enhancement

#20 staging: production
  .env
  README.md
  assets/hallo.png
  components/Common/DropdownMenu.tsx
  components/Common/TextField.tsx
  components/Footbar/index.tsx
  components/Image/index.tsx
  components/Navbar/index.tsx
  devenv.lock
  devenv.nix
  docker-compose.yaml
  layouts/Auth/AuthLayouts.tsx
  layouts/Auth/types.d.ts
  layouts/Base/BaseLayouts.tsx
  next.config.js
  package.json
  pages/_app.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/index.tsx
  prisma/migrations/20230212104137_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  utilities/contant/index.ts
  yarn.lock
Labels: documentation

#22 Fenny Oktaviani | Add component button & Improvement Landing Page
  assets/hallo.png
  assets/wellcome.png
  components/Common/Button.tsx
  components/Common/DropdownMenu.tsx
  components/Footbar/index.tsx
  components/Image/index.tsx
  components/Navbar/index.tsx
  layouts/Base/BaseLayouts.tsx
  pages/index.tsx
  utilities/interfaces/index.ts
Labels: enhancement

#24 merge : staging production
  README.md
  assets/hallo.png
  assets/wellcome.png
  components/Common/Button.tsx
  components/Common/DropdownMenu.tsx
  components/Footbar/index.tsx
  components/Image/index.tsx
  components/Navbar/index.tsx
  layouts/Base/BaseLayouts.tsx
  modules/Landing/index.tsx
  pages/index.tsx
  utilities/interfaces/index.ts
Labels: enhancement

#27 Fenny Oktaviani | Improvement Page Auth
  components/Common/Button.tsx
  components/Footbar/index.tsx
  modules/Landing/index.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
  utilities/interfaces/index.ts
Labels: enhancement

#32 feature: slicing login
  devenv.nix
  layouts/Auth/AuthLayouts.tsx
  layouts/Auth/index.tsx
  layouts/Base/BaseLayouts.tsx
  layouts/Base/index.tsx
  layouts/Base/types.d.ts
  modules/Landing/index.tsx
  package.json
  pages/auth/login.tsx
  pages/auth/register.tsx
  pages/index.tsx
  prisma/migrations/20230212104137_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  public/bg.svg
  public/logo.png
  tailwind.config.js
  yarn.lock
Labels: documentation
